### ISSUE TITLE
Error when using Twig Filter

### ISSUE THREAD

**Issue by JeanLucEsser** [tijsvanerp/craft-autolink#10]
Looks like it awaits a `Craft\string`.
I don't have anything special setup. The is a simple Redactor content.
Do you know what's going on ?

I simply call the Twig Filter like such: `{{ entry.postLead | autoLink }}`
I'm on the latest stable version of Craft 2.6.x

```
Argument 1 passed to Craft\ContentParser::__construct() must be an instance of Craft\string, string given, called in /home/aleniumcam/craft/plugins/autolink/services/AutoLinkService.php on line 59
```

**Comment by tijsvanerp** [comment]
Which version of php are you using? It looks a bit like you're using a version below 7

**Comment by JeanLucEsser** [comment]
I'll upgrade to 7.1 and get back. But that's probably it. Thanks.
PS: Didn't see any minimum requirements.

**Comment by JeanLucEsser** [comment]
Works perfectly fine now, thank you.
Have an enhancement request, will open another issue for it.
